export const sorts = [
  { title: "", sort: "" },
  { title: "Korean Drama", sort: "Korea" },
  { title: "Chinese Drama", sort: "Chinese" },
  { title: "Action Movies", sort: "action" },
  { title: "Zombie", sort: "zombie" },
  { title: "Japanese Drama", sort: "Japan" },
  { title: "American Movies", sort: "America" },
  { title: "Funny", sort: "funny" },
  { title: "Kids", sort: "kids" },
  { title: "Game", sort: "Game" },
  { title: "Vampire", sort: "vampire" },
  { title: "Romance", sort: "romance" },
  { title: "Adult", sort: "adult" },
  { title: "Fantasy", sort: "fantasy" },
  { title: "Avengers", sort: "avengers" },
  { title: "Gospel", sort: "gospel" },
  { title: "Music Video", sort: "music" },
  { title: "2000-till date", sort: "2002" },
  { title: "2010-till date", sort: "2010" },
];
